language: python
python:
  - '3.8'
env:
  - TOXENV=quality
  - TOXENV=docs
  - TOXENV=pii_check
  - TOXENV=django22
  - TOXENV=django30
  - TOXENV=django31
  - TOXENV=django32
cache:
  - pip
install:
  - pip install -r requirements/travis.txt
script:
  - tox
after_success:
  - codecov
deploy:
  provider: pypi
  user: edx
  distributions: sdist bdist_wheel
  on:
    tags: true
    python: 3.8
    condition: $TOXENV = quality
  password:
    secure: rh1C0D29KRN7O7CFFNajMnlSeIhbuArdF4VKLsPjR+GlfoSjKur0j2CdJGd0znr5vlNAQFgSHMLwGWhCrIFSTu6HUFT8PJhfVZ2M7IFDMwleq2k1aLYyk54ZVtZfVuy50c1uaS1CjTGJ55kccNYPrMf+CQCi/DZRe1MeogX3D1C7OtksyneRjPtIdz+l2jiqcwrrwDAJgOqSwONmgc1gI7HWHd4xLZinu/JeTLkYh3gTUBVBqv52reNbO3J4PUu+tFX37FTZnEebC5dLJyHFPJ89Fqz3gJDXwcUDcvtWhnWKjt9Hi+Xa8UvycdUygPuFMPfq8U2sLHX1L61WIODimpj66qGVgSK2B1vltqfvAFq5FS9g7ivzG3K6ANq4c/csouJv8ib6/J7J/G4ubsqgcFtBM3ag+T+dTTx8cNBskK2JhX6UMARh+zPkTTWpepqla30axMT9jTZ0O8PqgzbrtvWMxBssfbUpmu2WjpdL8KA8YFsEksY42gN+sFxNp45m31ABsIiaWc38GrHYibWt2BT/PThXroysQygwq38jQX6jIGnq6BPFY22XdTtll9xPTyKAcBQPOMNdhaBQME9h1QbNuyCFLgmsBfzrSIMA6pZGdthiwB/L3Jj11NNatf/bL0LnjpzIRywecLOeIvUo3agnIoTVymyLu/2zUZqWd7E=
