# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-18 17:36
from __future__ import absolute_import, unicode_literals

import django.db.models.deletion
import opaque_keys.edx.django.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edx_when', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdate',
            name='policy',
        ),
        migrations.AddField(
            model_name='contentdate',
            name='active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name='contentdate',
            name='field',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='userdate',
            name='content_date',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='edx_when.ContentDate'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contentdate',
            name='location',
            field=opaque_keys.edx.django.models.UsageKeyField(db_index=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='datepolicy',
            name='abs_date',
            field=models.DateTimeField(db_index=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='contentdate',
            unique_together=set([('policy', 'location', 'field')]),
        ),
    ]
