# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-09-11 09:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edx_when', '0003_auto_20190402_1501'),
    ]

    operations = [
        migrations.AddField(
            model_name='datepolicy',
            name='rel_date',
            field=models.DurationField(db_index=True, null=True),
        ),
    ]
