# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-09-11 10:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edx_when', '0004_datepolicy_rel_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datepolicy',
            name='abs_date',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='datepolicy',
            name='rel_date',
            field=models.DurationField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='userdate',
            name='rel_date',
            field=models.DurationField(blank=True, db_index=True, null=True),
        ),
    ]
