# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-03-30 18:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edx_when', '0005_auto_20190911_1056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentdate',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
