# Generated by Django 2.2.12 on 2020-04-21 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edx_when', '0006_drop_active_index'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='datepolicy',
            options={'verbose_name_plural': 'Date policies'},
        ),
    ]
