# Generated by Django 4.2.22 on 2025-06-23 13:56

from django.db import migrations, models
import opaque_keys.edx.django.models


class Migration(migrations.Migration):

    dependencies = [
        ('edx_when', '0008_courseversion_block_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentdate',
            name='assignment_title',
            field=models.CharField(blank=True, db_index=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='contentdate',
            name='course_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='contentdate',
            name='subsection_name',
            field=models.CharField(blank=True, db_index=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='userdate',
            name='first_component_block_id',
            field=opaque_keys.edx.django.models.UsageKeyField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userdate',
            name='user_date_value',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddIndex(
            model_name='contentdate',
            index=models.Index(fields=['assignment_title', 'course_id'], name='edx_when_assignment_course_idx'),
        ),
        migrations.AddIndex(
            model_name='contentdate',
            index=models.Index(fields=['subsection_name', 'course_id'], name='edx_when_subsection_course_idx'),
        ),
        migrations.AddIndex(
            model_name='userdate',
            index=models.Index(fields=['user', 'first_component_block_id'], name='edx_when_user_first_block_idx'),
        ),
        migrations.AddIndex(
            model_name='userdate',
            index=models.Index(fields=['user_date_value', 'user'], name='edx_when_user_date_value_idx'),
        ),
    ]
