# Generated by Django 4.2.22 on 2025-08-20 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edx_when', '0009_contentdate_assignment_title_contentdate_course_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdate',
            name='is_content_gated',
            field=models.BooleanField(default=False),
        ),
    ]
